### PR TITLE
Code cleanup.

### PR DESCRIPTION
**Pull request by bzalasky**
- Removes git conflict markers.
- Adds unintentionally missing semi-colons.
- Makes whitespace more consistent.

### CODE REVIEW

**Comment by bzalasky** [comment]
Was evaluating different routers for Cycle and saw some low hanging fruit here.

**Comment by TylorS** [comment]
Awesome! Thanks for your time, and contributions. I'll look at them when I get home from work, and get them merged.

Also if you're looking for a router, myself and @HighOnDrive are working on a new router at [cycle-router](https://github.com/tylors/cycle-router). Even just your thoughts would be welcomed, especially on issue #1

**Comment by bzalasky** [comment]
Cool, I noticed that. It'd be great if we could focus our efforts in the same direction. I'm using Cycle on an internal project at Lookout to evaluate it for future projects, and the only negatives so far have been some of the question marks around architecture and drivers. I don't think we'd be able to commit to using it on a larger project until these kinds of things have been ironed out.

**Comment by TylorS** [comment]
Yes, cycle is definitely still evolving, and best practices are still emerging and being discussed. One of the goals of @HighOnDrive and I is to provide an application template that helps nudge developers in the right direction. However it will likely be tailored to using cycle-router and where that project is heading. 

I'm definitely open to discussing how I might be able to help you out and maybe alleviate some of your current issues with cycle. You can certainly open an issue if appropriate or you can certainly find me on gitter.

**Pull request merged**
